### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by Feeco-Li** [kiprobinson/chordomatic#3]
Just open an issues to say thanks.
and want you know 
you're absolute a genius.

please keep this app alive.
best wish to you.

**Comment by kiprobinson** [comment]
Thanks! Seeing this reminded me of another guitar-related script I had been meaning to put on GitHub. This one is much simpler, just generating printable blank guitar tabs. Check it out if you're interested: https://github.com/kiprobinson/tabGenerator
